import Head from 'next/head'
import Typewriter from 'typewriter-effect';

export default function Home({dataUsers} : any) {
  const strings = [
    'Selamat datang di web blog saya',
    'Selamat melihat-lihat',
  ];

  return (
    <>
      <Head>
        <title>Indah Wisata</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div className='bg-blue-500 p-10 '>
            <div className="text-3xl text-white text-center font-bold mb-8">
                <Typewriter
                    options={{
                        autoStart: true,
                        loop: true,
                    }}
                    onInit={(typewriter) => {
                        typewriter
                        .typeString(strings[0])
                        .pauseFor(2000)
                        .deleteAll()
                        .pauseFor(2000)
                        .typeString(strings[1])
                        .pauseFor(2000)
                        .deleteAll()
                        .pauseFor(2000)
                        .start();
                    }}
                />
            </div>
            <ul className='lg:grid lg:grid-cols-3 lg:gap-x-6 '>
                {dataUsers.data.map((user:any) => (
                    <li key={user.id}>
                        <div className='max-w-sm rounded overflow-hidden drop-shadow-xl bg-white m-auto'>
                            <img className='w-full' src={`https://eyns69u2.directus.app/assets/${user.image}`}/>
                            <div className='px-6 py-4'>
                                <h1 className='font-bold text-xl mb-2'>
                                    {user.name}
                                </h1>
                                <p className='text-gray-700 text-base'>
                                    {user.description}
                                </p>
                            </div>
                        </div><br /><br />
                    </li>
                ))}
            </ul>
        </div>
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch('https://eyns69u2.directus.app/items/vacation');
  const dataUsers = await res.json();
  return {
      props: {
      dataUsers,
      },
  };
}